/* This file is generated by Ziggy. */
declare module 'ziggy-js' {
  interface RouteList {
    "sanctum.csrf-cookie": [],
    "dashboard": [],
    "categories.index": [],
    "categories.store": [],
    "categories.edit": [
        {
            "name": "category",
            "required": true,
            "binding": "id"
        }
    ],
    "categories.update": [
        {
            "name": "category",
            "required": true,
            "binding": "id"
        }
    ],
    "categories.destroy": [
        {
            "name": "category",
            "required": true,
            "binding": "id"
        }
    ],
    "patients.index": [],
    "patients.store": [],
    "patients.edit": [
        {
            "name": "patient",
            "required": true
        }
    ],
    "patients.update": [
        {
            "name": "patient",
            "required": true
        }
    ],
    "patients.destroy": [
        {
            "name": "patient",
            "required": true
        }
    ],
    "profile.edit": [],
    "profile.update": [],
    "profile.destroy": [],
    "login": [],
    "password.request": [],
    "password.email": [],
    "password.reset": [
        {
            "name": "token",
            "required": true
        }
    ],
    "password.store": [],
    "verification.notice": [],
    "verification.verify": [
        {
            "name": "id",
            "required": true
        },
        {
            "name": "hash",
            "required": true
        }
    ],
    "verification.send": [],
    "password.confirm": [],
    "password.update": [],
    "logout": [],
    "storage.local": [
        {
            "name": "path",
            "required": true
        }
    ],
    "storage.local.upload": [
        {
            "name": "path",
            "required": true
        }
    ]
}
}
export {};
