export interface OptionType {
    value?: string;
    label?: string;
    colSpan?: number;
    exclusive?: boolean;
    text?: string;
}

export const respiratorySymptoms: OptionType[] = [
    { value: 'NORMAL', label: 'Normal', exclusive: true, colSpan: 12 },
    { value: 'COUGH', label: 'Cough', colSpan: 3 },
    { value: 'DYSPNEA', label: 'Dyspnea', colSpan: 3 },
    { value: 'TACHYPNEA', label: 'Tachypnea', colSpan: 3 },
    { value: 'BRADYSPNEA', label: 'Bradyspnea', colSpan: 3 },
    { value: 'RUNNY_NOSE', label: 'Runny nose', colSpan: 3 },
    { value: 'DIFFICULTY_BREATHING', label: 'Difficulty breathing', colSpan: 3 },
    { value: 'APNEA', label: 'Apnea', colSpan: 3 },
    { value: 'SNORING', label: 'Snoring', colSpan: 3 },
    { value: 'NASAL_FLARING', label: 'Nasal flaring', colSpan: 3 },
    { value: 'STRIDOR', label: 'Stridor', colSpan: 3 },
    { value: 'CYANOSIS', label: 'Cyanosis', colSpan: 3 },
    { value: 'THORAX_ASYMMETRICAL', label: 'Thorax asymmetrical', colSpan: 3 },
    { value: 'INSUFFICIENT_RESPIRATORY_EFFORT', label: 'Insufficient respiratory effort', colSpan: 12 },
    { text: 'Chest retraction' },
    { value: 'SUPRASTERNAL', label: 'Suprasternal', colSpan: 3 },
    { value: 'SUPRACLAVICULAR', label: 'Supraclavicular', colSpan: 3 },
    { value: 'INTERCOSTAL', label: 'Intercostal', colSpan: 3 },
    { value: 'SUBCOSTAL', label: 'Subcostal', colSpan: 3 },
    { value: 'SUBSTERNAL', label: 'Substernal', colSpan: 3 },
    { text: 'Breathing sound' },
    { value: 'CRACKLE', label: 'Crackle', colSpan: 3 },
    { value: 'CRACKLE_RIGHT_SIDE', label: 'Right side', colSpan: 3 },
    { value: 'CRACKLE_LEFT_SIDE', label: 'Left side', colSpan: 3 },
    { value: 'WHEEZING', label: 'Wheezing', colSpan: 3 },
    { value: 'WHEEZING_RIGHT_SIDE', label: 'Right side', colSpan: 3 },
    { value: 'WHEEZING_LEFT_SIDE', label: 'Left side', colSpan: 3 },
    { value: 'PLEURAL_FRICTION_RUB', label: 'Pleural friction rub', colSpan: 3 },
    { value: 'PLEURAL_FRICTION_RUB_RIGHT_SIDE', label: 'Right side', colSpan: 3 },
    { value: 'PLEURAL_FRICTION_RUB_LEFT_SIDE', label: 'Left side', colSpan: 3 },
    { value: 'DECREASE_AIR_ENTRY', label: 'Decrease air entry', colSpan: 3 },
    { value: 'DECREASE_AIR_ENTRY_RIGHT_SIDE', label: 'Right side', colSpan: 3 },
    { value: 'DECREASE_AIR_ENTRY_LEFT_SIDE', label: 'Left side', colSpan: 3 },
    { text: 'SpO2' },
    { value: 'O2_SUPPLY', label: 'O2 Supply', colSpan: 3 },
    { value: 'NASAL_CANNULA', label: 'Nasal Cannula', colSpan: 3 },
    { text: 'Chest tube' },
    { value: 'CHEST_TUBE_RIGHT_SIDE', label: 'Right side', colSpan: 3 },
    { value: 'CHEST_TUBE_LEFT_SIDE', label: 'Left side', colSpan: 3 },
];

export const cardiovascularSymptoms: OptionType[] = [
    { value: 'NORMAL', label: 'Normal', exclusive: true, colSpan: 12 },
    { value: 'TACHYCARDIA', label: 'Tachycardia', colSpan: 3 },
    { value: 'BRADYCARDIA', label: 'Bradycardia', colSpan: 3 },
    { value: 'MURMUR', label: 'Murmur', colSpan: 3 },
    { value: 'CHEST_PAIN', label: 'Chest pain', colSpan: 3 },
    { value: 'EDEMA', label: 'Edema', colSpan: 3 },
    { value: 'PALPITATIONS', label: 'Palpitations', colSpan: 3 },
    { value: 'PALE', label: 'Pale', colSpan: 3 },
    { value: 'PULSE_WEAKNESS', label: 'Pulse weakness', colSpan: 3 },
    { value: 'COOL_EXTREMITY', label: 'Cool extremity', colSpan: 3 },
    { value: 'CYANOSIS_EXTREMITY', label: 'Cyanosis extremity', colSpan: 3 },
    { value: 'CRP_GREATER_2_SEC', label: 'CRP > 2 Sec', colSpan: 3 },
    { value: 'BOUNDING_PLUSE', label: 'Bounding Pluse', colSpan: 3 },
    { value: 'HYPERTENSION', label: 'Hypertension', colSpan: 3 },
    { value: 'HYPOTENSION', label: 'Hypotension', colSpan: 3 },
];

export const neurologicalSymptoms: OptionType[] = [
    { value: 'NORMAL', label: 'Normal', exclusive: true, colSpan: 12 },
    { text: 'Anterior fontanelle' },
    { value: 'BULGING', label: 'Bulging', colSpan: 3 },
    { value: 'SUNKEN', label: 'Sunken', colSpan: 3 },
    { text: 'Consciousness level' },
    { value: 'CONSCIOUSNESS', label: 'Consciousness', colSpan: 3 },
    { value: 'DELIRIUM', label: 'Delirium', colSpan: 3 },
    { value: 'COMA', label: 'Coma', colSpan: 3 },
    { value: 'CONVULSION', label: 'Convulsion', colSpan: 3 },
    { value: 'HEAD_ACHE', label: 'Head ache', colSpan: 3 },
    { value: 'DIZZINESS', label: 'Dizziness', colSpan: 3 },
    { value: 'NUMBNESS', label: 'Numbness', colSpan: 3 },
    { value: 'LETHARGY', label: 'Lethargy', colSpan: 3 },
    { value: 'LOOS_OF_BALANCE', label: 'Loos of balance', colSpan: 3 },
    { value: 'PARALYSIS', label: 'Paralysis', colSpan: 3 },
    { value: 'TREMORS', label: 'Tremors', colSpan: 3 },
    { value: 'CONFUSION', label: 'Confusion', colSpan: 3 },
    { value: 'DYSPHASIA', label: 'Dysphasia', colSpan: 3 },
    { text: 'Extremities Movement' },
    { value: 'WEAK', label: 'Weak', colSpan: 3 },
    { value: 'ABSENCE', label: 'Absence', colSpan: 3 },
    { value: 'LIMIT_RANGE_OF_MOVEMENT', label: 'Limit range of movement', colSpan: 3 },
];

export const musculoskeletalSymptoms: OptionType[] = [
    { value: 'NORMAL', label: 'Normal', exclusive: true, colSpan: 12 },
    { value: 'EDEMA_SWOLLEN', label: 'Edema / Swollen', colSpan: 3 },
    { value: 'PAIN_CRAMP', label: 'Pain / Cramp', colSpan: 3 },
    { value: 'CONTRACTURE', label: 'Contracture', colSpan: 3 },
    { value: 'BONE_PAIN', label: 'Bone pain', colSpan: 3 },
    { value: 'JOINT_PAINT', label: 'Joint pain', colSpan: 3 },
    { value: 'JOINT_STIFFNESS', label: 'Joint Stiffness', colSpan: 3 },
    { value: 'LIMITED_MOVEMENT', label: 'Limited movement', colSpan: 3 },
    { value: 'DECREASE_BALANCE', label: 'Decrease balance', colSpan: 3 },
    { value: 'GAIT', label: 'Gait (ថយចុះការដើរ)', colSpan: 3 },
    { text: 'Type of bone fracture' },
    { value: 'CLOSE_FRACTURE', label: 'Close fracture', colSpan: 3 },
    { value: 'OPEN_FRACTURE', label: 'Open fracture', colSpan: 3 },
    { value: 'AMPUTATION', label: 'Amputation', colSpan: 3 },
    { value: 'PROSTHESIS', label: 'Prosthesis', colSpan: 3 },
    { value: 'ASSISTIVE_DEVICE', label: 'Assistive device', colSpan: 3 },
];

export const digestiveSymptoms: OptionType[] = [
    { value: 'NORMAL', label: 'Normal', exclusive: true, colSpan: 12 },
    { value: 'NAUSEA', label: 'Nausea', colSpan: 3 },
    { value: 'ABDOMINAL_PAIN', label: 'Abdominal pain', colSpan: 3 },
    { value: 'ABDOMINAL_DISTENSION', label: 'Abdominal distension', colSpan: 3 },
    { value: 'SWALLOWING_DIFFICULTY', label: 'Swallowing difficulty', colSpan: 3 },
    { value: 'VOMITING', label: 'Vomiting', colSpan: 3 },
    { value: 'HEMATEMESIS', label: 'Hematemesis', colSpan: 3 },
    { value: 'POOR_APPETITE', label: 'Poor appetite', colSpan: 3 },
    { value: 'HEPATOMEGALY', label: 'Hepatomegaly', colSpan: 3 },
    { value: 'SPLENOMEGALY', label: 'Splenomegaly', colSpan: 3 },
    { text: 'Change bowel sound' },
    { value: 'BOWEL_SOUND_DECREASE', label: 'Decrease', colSpan: 3 },
    { value: 'BOWEL_SOUND_INCREASE', label: 'Increase', colSpan: 3 },
    { value: 'BOWEL_SOUND_ABSENCE', label: 'Absence', colSpan: 3 },
    { text: 'Abnormal stool' },
    { value: 'DIARRHEA', label: 'Diarrhea', colSpan: 3 },
    { value: 'CONSTIPATION', label: 'Constipation', colSpan: 3 },
    { value: 'BLACK_STOOL', label: 'Black stool', colSpan: 3 },
    { value: 'BLOODY_STOOL', label: 'Bloody stool', colSpan: 3 },
];

export const renalReproductiveSymptoms: OptionType[] = [
    { value: 'NORMAL', label: 'Normal', exclusive: true, colSpan: 12 },
    { text: 'Abnormal urinary color' },
    { value: 'CLOUDY', label: 'Cloudy', colSpan: 3 },
    { value: 'DARK_YELLOW', label: 'Dark yellow', colSpan: 3 },
    { value: 'DARK_BROWN', label: 'Dark brown', colSpan: 3 },
    { value: 'RED', label: 'Red', colSpan: 3 },
    { value: 'DYSURIA', label: 'Dysuria', colSpan: 3 },
    { value: 'POLLAKIURIA', label: 'Pollakiuria', colSpan: 3 },
    { value: 'HEMATURIA', label: 'Hematuria', colSpan: 3 },
    { value: 'POLYURIA', label: 'Polyuria', colSpan: 3 },
    { value: 'URINARY_OBSTRUCTION', label: 'Urinary obstruction', colSpan: 3 },
    { value: 'ANURIA_NO_URINE_LESS_THAN_24_HS', label: 'Anuria (No urine > 24 hs)', colSpan: 3 },
    { value: 'OILGURIA_LESS_THAN_24H', label: 'Oilguria < 400ml / 24h', colSpan: 3 },
    { value: 'URINARY_INCONTINENCE', label: 'Urinary incontinence', colSpan: 3 },
    { value: 'ABNORMAL_URINARY_COLOR_ODOR', label: 'Odor', colSpan: 3 },
    { value: 'ABNORMAL_URINARY_COLOR_PYURIA', label: 'Pyuria', colSpan: 3 },
    { value: 'PROSTATE_PROBLEM', label: 'Prostate problem', colSpan: 3 },
    { text: 'Reproductive' },
    { value: 'GENITAL_DISCHARGE', label: 'Genital discharge', colSpan: 3 },
    { value: 'PAIN_AROUND_GENITAL', label: 'Pain around genital', colSpan: 3 },
    { value: 'ITCHING', label: 'Itching', colSpan: 3 },
    { value: 'GENITAL_INFECTION', label: 'Genital infection', colSpan: 3 },
    { value: 'BLISTER', label: 'Blister', colSpan: 3 },
    { value: 'SORE', label: 'Sore', colSpan: 3 },
    { value: 'REPRODUCTIVE_ODOR', label: 'Odor', colSpan: 3 },
];

export const skinSymptoms: OptionType[] = [
    { value: 'NORMAL', label: 'Normal', exclusive: true, colSpan: 12 },
    { value: 'SKIN_LESIONS', label: 'Skin lesions', colSpan: 3 },
    { value: 'REDNESS', label: 'Redness', colSpan: 3 },
    { value: 'SKIN_BLISTER', label: 'Blister', colSpan: 3 },
    { value: 'JAUNDICE', label: 'Jaundice', colSpan: 3 },
    { value: 'BURN', label: 'Burn', colSpan: 3 },
    { value: 'DRY_SKIN', label: 'Dry skin', colSpan: 3 },
    { value: 'DECREASE_TURGOR', label: 'Decrease turgor', colSpan: 3 },
    { value: 'SKIN_MOTTLING', label: 'Skin mottling', colSpan: 3 },
    { value: 'RASH', label: 'Rash', colSpan: 3 },
    { value: 'ACROCYANOSIS', label: 'ស្វាយចុងដៃចុងជើង', colSpan: 3 },
    { value: 'HYPERTHERMIA', label: 'Hyperthermia', colSpan: 3 },
    { value: 'HYPOTHERMIA', label: 'Hypothermia', colSpan: 3 },
    { value: 'PETECHIAL', label: 'Petechial', colSpan: 3 },
    { value: 'SWELLING', label: 'Swelling', colSpan: 3 },
];

export const eyeSymptoms: OptionType[] = [
    { value: 'NORMAL', label: 'Normal', exclusive: true, colSpan: 12 },
    { value: 'EPIPHORA', label: 'ហូរទឹកភ្នែក', colSpan: 3 },
    { value: 'OCULAR_PAIN', label: 'ឈឺភ្នែក', colSpan: 3 },
    { value: 'RED_EYE', label: 'Red eye', colSpan: 3 },
    { value: 'YELLOW_EYE', label: 'Yellow eye', colSpan: 3 },
    { value: 'SUB_CONJUNCTIVAL_HEMORRHAGE', label: 'Sub conjunctival hemorrhage', colSpan: 3 },
    { value: 'BLURRY_VISION', label: 'Blurry vision', colSpan: 3 },
    { value: 'OCULAR_PRURITUS', label: 'រកាំភ្នែក', colSpan: 3 },
    { value: 'ITCHING', label: 'Itching', colSpan: 3 },
    { value: 'EYELID_EDEMA', label: 'ហើមត្របក់ភ្នែក', colSpan: 3 },
    { value: 'CORNEAL_OPACITY', label: 'មានឡើងសក្នុងប្រស្រីភ្នែក', colSpan: 3 },
    { value: 'EYELID_MASS', label: 'ឡើងដុំលើត្របក់ភ្នែក', colSpan: 3 },
    { value: 'BLURRED_VISION', label: 'ពពឹកភ្នែក', colSpan: 3 },
    { value: 'DACRYOCYSTITIS', label: 'ខ្ទុះនៅថង់ទឹកភ្នែក', colSpan: 3 },
    { value: 'PTOSIS', label: 'ធ្លាក់ត្របកភ្នែក', colSpan: 3 },
    { value: 'EXOPHTHALMIA', label: 'Exophthalmia', colSpan: 3 },
    { value: 'LAGOPHTHALMOS', label: 'បិទភ្នែកអត់ជិត', colSpan: 3 },
];

export const earSymptoms: OptionType[] = [
    { value: 'NORMAL', label: 'Normal', exclusive: true, colSpan: 12 },
    { value: 'HEARING_IMPAIRMENT', label: 'ផ្លាស់ផ្តូរការលឺ', colSpan: 3 },
    { value: 'DIZZINESS', label: 'ថ្លង់', colSpan: 3 },
    { value: 'OTALGIA', label: 'ឈឺត្រចៀក', colSpan: 3 },
    { value: 'EAR_DISCHARGE', label: 'Ear discharge', colSpan: 3 },
    { value: 'OTORRHEA', label: 'ហឹងត្រចៀក', colSpan: 3 },
    { value: 'HEARING_LOSS', label: 'Hearing loss', colSpan: 3 },
    { value: 'EAR_FULLNESS', label: 'Ear fullness', colSpan: 3 },
    { value: 'EAR_ITCHING', label: 'Ear Itching', colSpan: 3 },
    { value: 'FURONCULOSIS', label: 'Furonculosis (របួសរន្ធត្រចៀក)', colSpan: 3 },
    { value: 'CORNEAL_OPACITY', label: 'មានឡើងសក្នុងប្រស្រីភ្នែក', colSpan: 3 },
];

export const noseSymptoms: OptionType[] = [
    { value: 'NORMAL', label: 'Normal', exclusive: true, colSpan: 12 },
    { value: 'RUNNY_NOSE', label: 'Runny nose', colSpan: 3 },
    { value: 'NOSE_BLEEDING', label: 'Nose bleeding', colSpan: 3 },
    { value: 'STUFFY_NOSE', label: 'Stuffy nose', colSpan: 3 },
    { value: 'SINUS_PAIN', label: 'Sinus pain', colSpan: 3 },
    { value: 'FETOR_NASAL', label: 'ធំក្លិនច្រមុះ', colSpan: 3 },
    { value: 'NASAL_OBSTRUCTION', label: 'Nasal Obstruction', colSpan: 3 },
    { value: 'NOSE_IRRITATION', label: 'Nose irritation', colSpan: 3 },
    { value: 'SNEEZING', label: 'Sneezing', colSpan: 3 },
    { value: 'ANOSMIA', label: 'Anosmia (បាត់ក្លិន)', colSpan: 3 },
    { value: 'CACOSMIA', label: 'Cacosmia', colSpan: 3 },
    { value: 'FACIAL_PAIN', label: 'Facial pain', colSpan: 3 },
];

export const throatSymptoms: OptionType[] = [
    { value: 'NORMAL', label: 'Normal', exclusive: true, colSpan: 12 },
    { value: 'GUM_BLEEDING', label: 'Gum bleeding', colSpan: 3 },
    { value: 'THROAT_PAIN', label: 'Pain', colSpan: 3 },
    { value: 'SORE_THROAT', label: 'Sore throat', colSpan: 3 },
    { value: 'SPEECH_DISORDER', label: 'ពិបាកនិយាយ', colSpan: 3 },
    { value: 'DYSPHAGIA', label: 'Dysphagia', colSpan: 3 },
    { value: 'ORAL_MUCOSA_STIFFNESS', label: 'រឹងថ្គាម', colSpan: 3 },
    { value: 'ODYNOPHALGIA', label: 'ឈឺពេលលេបអាហារ', colSpan: 3 },
    { value: 'HYPERSECRETAION', label: 'Hypersecretaion', colSpan: 3 },
    { value: 'THROAT_COUGH', label: 'Cough', colSpan: 3 },
    { value: 'DYSPHONIA', label: 'សំឡេងស្អក', colSpan: 3 },
    { value: 'TOOTH_PAIN', label: 'Tooth pain', colSpan: 3 },
    { value: 'DENTAL_CARIES', label: 'ពុកធ្មេញ', colSpan: 3 },
];

export const psycologySymptoms: OptionType[] = [
    { value: 'LETHARGY', label: 'ស្លូត', colSpan: 3 },
    { value: 'AGITATION', label: 'ឆេវឆាវ', colSpan: 3 },
    { value: 'ISOLATION', label: 'Isolation', colSpan: 3 },
    { value: 'ANXIETY', label: 'Anxiety', colSpan: 3 },
    { value: 'HALLUCINATION', label: 'Hallucination', colSpan: 3 },
];
